version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - dependencies
    versioning-strategy: increase
    reviewers:
      - "KristenKatona"
      - "nicogonza"
    ignore:
      - dependency-name: "@types/node"
        versions:
          - ">= 10"
  - package-ecosystem: "github-actions"
     open-pull-requests-limit: 10
    directory: "/"
    reviewers:
      - "KristenKatona"
      - "nicogonza"
    schedule:
      interval: "daily"
